name: Build

on:
  workflow_call:

env:
  AZURE_FUNCTIONAPP_NAME: HttpTrigger1 # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: 6.0.202

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: ✔️ Checkout repo at triggering ref
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: 🔌Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 🔨 Build app
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: ⬆️ Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: output
