name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'hotfix\/[0-9]+.[0-9]+.[0-9]+'
      - 'release\/[0-9]+.[0-9]+.[0-9]+'
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+-**'
    pull_request:
      types: [opened, edited]
    paths-ignore:
      - '**/**.md'

permissions:
  id-token: write
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yml
  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
